# Generated by Django 4.1a1 on 2022-05-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200, null=True)),
                ('property', models.DecimalField(decimal_places=8, max_digits=28)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('contact_name', models.CharField(max_length=200, null=True)),
                ('contact_phone_number', models.CharField(max_length=200, null=True)),
                ('contact_email', models.CharField(max_length=200, null=True)),
                ('contact_relationship', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('hiredate', models.DateField(null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=28)),
                ('interest_rate', models.DecimalField(decimal_places=8, max_digits=28)),
                ('open_date', models.DateField(null=True)),
                ('last_access_date', models.DateField(null=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.branch')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.branch')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.staff')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.staff'),
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=28)),
                ('overdraft', models.DecimalField(decimal_places=8, max_digits=28)),
                ('open_date', models.DateField(null=True)),
                ('last_access_date', models.DateField(null=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.branch')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.loan')),
            ],
            options={
                'unique_together': {('loan_id', 'release_date')},
            },
        ),
        migrations.CreateModel(
            name='Client_Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.client')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.loan')),
            ],
            options={
                'unique_together': {('client_id', 'loan_id')},
            },
        ),
        migrations.CreateModel(
            name='Client_Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.branch')),
                ('checking_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.checkingaccount')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.client')),
                ('saving_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.savingaccount')),
            ],
            options={
                'unique_together': {('client_id', 'branch_name')},
            },
        ),
    ]
