# Generated by Django 4.1a1 on 2022-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='last_access_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loanrelease',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='last_access_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hiredate',
            field=models.DateTimeField(null=True),
        ),
    ]
