# Generated by Django 4.1a1 on 2022-06-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_checkingaccount_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loanrelease',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='loan',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrelease',
            name='client_loan_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='api.client_loan'),
        ),
        migrations.AlterUniqueTogether(
            name='loanrelease',
            unique_together={('client_loan_id', 'release_date')},
        ),
        migrations.RemoveField(
            model_name='loanrelease',
            name='loan_id',
        ),
    ]
