# Generated by Django 4.1a1 on 2022-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_loanrelease_unique_together_loan_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='done',
        ),
        migrations.AddField(
            model_name='loan',
            name='release_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
    ]
