# Generated by Django 4.1a1 on 2022-06-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_loan_done_loan_release_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='release_amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='total',
        ),
    ]
