# Generated by Django 4.1a1 on 2022-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_release_amount_loan_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=models.DecimalField(decimal_places=8, max_digits=28), max_digits=28),
        ),
    ]
